language: java
jdk: openjdk11

branches:
  only:
    - master
    - develop
    - /\d+\.\d+\.\d+/

notifications:
  email:
    on_success: never
    on_failure: never

deploy:
  - provider: releases
    api_key: $GITHUB_OAUTH_TOKEN
    file_glob: true
    file:
    - img2excel-cli/target/*.jar
    - target/LICENSE
    - target/README.md
    skip_cleanup: true
    on:
      tags: true
      all_branches: false

